name: "Flake Check"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flake-dirs: ["user_service", "workout_service", "meal_service"]
    defaults:
      run:
        working-directory: ${{ matrix.flake-dirs }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check all systems
        run: nix flake check --all-systems
      - name: Nix flake build
        run: nix build
